"""packaging/windows/build.py — the pure helpers of the Windows build.

Why these tests exist
---------------------
The Windows distribution is assembled on Linux and can only be *run* on a
Windows machine, so everything that can be checked without one is checked
here: the ``._pth`` search path, the requirements filter behind the
``MINIDSP_LINUX_WHEEL`` override, the PySide6 allow-list prune, the DLL
import-closure rule that guards the prune, the PE import reader that feeds
it, and the structural check the build applies to its own zip. No network,
no ``makensis``, no cross-compiler: every test runs on a fake tree.
"""

from __future__ import annotations

import importlib.util
import struct
import sys
from pathlib import Path

import pytest

_BUILD_PY = Path(__file__).resolve().parents[1] / "packaging" / "windows" / "build.py"
_spec = importlib.util.spec_from_file_location("windows_build", _BUILD_PY)
wb = importlib.util.module_from_spec(_spec)
sys.modules["windows_build"] = wb
_spec.loader.exec_module(wb)


# --- version and naming ----------------------------------------------------------


def test_project_version_reads_pyproject(tmp_path):
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text('[project]\nname = "x"\nversion = "1.4.2"\n')
    assert wb.project_version(pyproject) == "1.4.2"


@pytest.mark.parametrize(
    "version, expected",
    [("1.2.3", (1, 2, 3)), ("1.2.0-rc1", (1, 2, 0)), ("2.0", (2, 0, 0)), ("1.0.0+local", (1, 0, 0))],
)
def test_version_tuple_drops_prerelease_and_pads(version, expected):
    assert wb.version_tuple(version) == expected


def test_python_version_helpers():
    assert wb.short_version("3.13.15") == "3.13"
    assert wb.dll_digits("3.13.15") == "313"


def test_artifact_names():
    zip_name, setup_name, top = wb.artifact_names("1.2.0")
    assert zip_name == "minidspqt-1.2.0-win_amd64.zip"
    assert setup_name == "minidspqt-1.2.0-win_amd64-setup.exe"
    assert top == "minidspqt-1.2.0"


def test_pth_content_is_isolated_stdlib_app_dir_and_site_packages():
    text = wb.pth_content("3.13.15")
    # "." is where the embeddable distribution keeps _ctypes.pyd and friends.
    assert text.splitlines() == ["python313.zip", ".", "Lib\\site-packages"]
    assert "import site" not in text


def _fake_app_dir(tmp_path: Path) -> Path:
    app = tmp_path / "app"
    (app / "Lib" / "site-packages").mkdir(parents=True)
    for name in ("python313.zip", "python313.dll", "_ctypes.pyd", "_socket.pyd"):
        (app / name).write_bytes(b"x")
    return app


def test_check_search_path_accepts_the_generated_pth(tmp_path):
    app = _fake_app_dir(tmp_path)
    assert wb.check_search_path(app, wb.pth_content("3.13.15")) == []


def test_check_search_path_catches_a_missing_app_dir_entry(tmp_path):
    app = _fake_app_dir(tmp_path)
    problems = wb.check_search_path(app, "python313.zip\nLib\\site-packages\n")
    assert any("_ctypes.pyd" in p and "'.'" in p for p in problems)


def test_check_search_path_catches_missing_entries(tmp_path):
    app = _fake_app_dir(tmp_path)
    problems = "\n".join(wb.check_search_path(app, "python313.zip\n.\nLib\\typo\n"))
    assert "does not exist: Lib\\typo" in problems
    assert "site-packages is not on sys.path" in problems


def test_render_template_fills_and_rejects_leftovers():
    assert wb.render_template("v=@VERSION@ m=@MAJOR@", {"VERSION": "1.2.3", "MAJOR": "1"}) == "v=1.2.3 m=1"
    with pytest.raises(wb.BuildError, match="@MINOR@"):
        wb.render_template("@VERSION@ @MINOR@", {"VERSION": "1.2.3"})


# --- requirements filter (MINIDSP_LINUX_WHEEL override) ----------------------------

_EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-dev --no-emit-project --no-hashes
markdown-it-py==4.2.0
    # via rich
minidsp-linux @ https://github.com/IMBArator/miniDSP-Linux/releases/download/v1.2.0/minidsp_linux-1.2.0-py3-none-any.whl
    # via minidsp-linux-qt
pyside6-essentials==6.11.0
    # via minidsp-linux-qt
rich==15.0.0
    # via minidsp-linux
hidapi==0.15.0 ; sys_platform == 'win32'
    # via minidsp-linux
"""


def test_filter_requirements_drops_the_pin_and_its_via_comment():
    out = wb.filter_requirements(_EXPORT, "minidsp-linux")
    assert "minidsp-linux @" not in out
    assert "# via minidsp-linux-qt\n" not in out.split("pyside6")[0]
    assert "pyside6-essentials==6.11.0\n    # via minidsp-linux-qt" in out
    assert "rich==15.0.0\n    # via minidsp-linux" in out
    assert "hidapi==0.15.0 ; sys_platform == 'win32'" in out
    assert out.startswith("# This file was autogenerated")


def test_filter_requirements_normalises_names_and_ignores_unknown():
    assert "minidsp-linux @" not in wb.filter_requirements(_EXPORT, "MiniDSP_Linux")
    assert wb.filter_requirements(_EXPORT, "not-there") == _EXPORT
    # A prefix must not match: "rich" is not "rich-extra".
    assert "rich==15.0.0" in wb.filter_requirements(_EXPORT, "rich-extra")


# --- Qt module scan -------------------------------------------------------------------


def test_qt_modules_used_scans_package_sources(tmp_path):
    pkg = tmp_path / "minidspqt"
    (pkg / "views").mkdir(parents=True)
    (pkg / "app.py").write_text("from PySide6.QtCore import QCoreApplication\n")
    (pkg / "views" / "w.py").write_text("from PySide6.QtWidgets import QWidget\nimport PySide6.QtGui\n")
    (pkg / "notes.txt").write_text("PySide6.QtNetwork is not code\n")
    assert wb.qt_modules_used(pkg) == {"QtCore", "QtWidgets", "QtGui"}


# --- prune ----------------------------------------------------------------------------

_KEEP = [
    "PySide6/__init__.py",
    "PySide6/_config.py",
    "PySide6/_git_pyside_version.py",
    "PySide6/PySide6_Essentials.json",
    "PySide6/QtCore.pyd",
    "PySide6/QtGui.pyd",
    "PySide6/QtWidgets.pyd",
    "PySide6/Qt6Core.dll",
    "PySide6/Qt6Gui.dll",
    "PySide6/Qt6Widgets.dll",
    "PySide6/Qt6Svg.dll",
    "PySide6/pyside6.abi3.dll",
    "PySide6/msvcp140.dll",
    "PySide6/msvcp140_1.dll",
    "PySide6/vcruntime140.dll",
    "PySide6/vcruntime140_1.dll",
    "PySide6/concrt140.dll",
    "PySide6/plugins/platforms/qwindows.dll",
    "PySide6/plugins/platforms/qoffscreen.dll",
    "PySide6/plugins/styles/qmodernwindowsstyle.dll",
    "PySide6/plugins/iconengines/qsvgicon.dll",
    "PySide6/plugins/imageformats/qsvg.dll",
    "PySide6/plugins/imageformats/qico.dll",
    "PySide6/plugins/imageformats/qjpeg.dll",
    "PySide6/plugins/imageformats/qgif.dll",
    "shiboken6/__init__.py",
    "shiboken6/_config.py",
    "shiboken6/Shiboken.pyd",
    "shiboken6/shiboken6.abi3.dll",
    "shiboken6/msvcp140.dll",
    "shiboken6/vcruntime140.dll",
]
_DROP = [
    "PySide6/QtQml.pyd",
    "PySide6/QtSvg.pyd",
    "PySide6/QtCore.pyi",
    "PySide6/Qt6Qml.dll",
    "PySide6/Qt6Quick.dll",
    "PySide6/Qt6Network.dll",
    "PySide6/pyside6qml.abi3.dll",
    "PySide6/pyside6.abi3.lib",
    "PySide6/opengl32sw.dll",
    "PySide6/vcomp140.dll",
    "PySide6/designer.exe",
    "PySide6/plugins/platforms/qdirect2d.dll",
    "PySide6/plugins/imageformats/qpdf.dll",
    "PySide6/plugins/sqldrivers/qsqlite.dll",
    "PySide6/plugins/tls/qschannelbackend.dll",
    "PySide6/qml/QtQuick/qtquick2plugin.dll",
    "PySide6/translations/qtbase_de.qm",
    "PySide6/resources/icudtl.dat",
    "PySide6/include/pyside.h",
    "PySide6/typesystems/typesystem_core.xml",
    "shiboken6/Shiboken.pyi",
    "shiboken6/include/sbkpython.h",
    "bin/pyside6-designer",
]
_OTHER = [
    "minidspqt/__init__.py",
    "minidspqt/resources/blank.unt",
    "minidsp/device.py",
    "hid.cp313-win_amd64.pyd",
    "minidsp_linux_qt-1.1.0.dist-info/METADATA",
]


def _fake_site_packages(tmp_path: Path, files=None) -> Path:
    site = tmp_path / "site-packages"
    for rel in files if files is not None else _KEEP + _DROP + _OTHER:
        path = site / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"x")
    return site


def test_prune_keeps_the_allow_list_and_removes_everything_else(tmp_path):
    site = _fake_site_packages(tmp_path)
    removed = wb.prune_site_packages(site)

    for rel in _KEEP + _OTHER:
        assert (site / rel).is_file(), f"{rel} should have been kept"
    for rel in _DROP:
        assert not (site / rel).exists(), f"{rel} should have been removed"
    assert {p.name for p in removed} >= {"QtQml.pyd", "designer.exe", "pyside6-designer"}
    # Emptied directories are gone; populated ones remain.
    for gone in ("PySide6/qml", "PySide6/translations", "PySide6/plugins/sqldrivers", "shiboken6/include", "bin"):
        assert not (site / gone).exists(), gone
    assert (site / "PySide6" / "plugins" / "imageformats").is_dir()


def test_prune_refuses_an_unexpected_layout(tmp_path):
    files = [f for f in _KEEP + _DROP + _OTHER if not f.endswith("qwindows.dll")]
    site = _fake_site_packages(tmp_path, files)
    with pytest.raises(wb.BuildError, match="qwindows.dll"):
        wb.prune_site_packages(site)
    # Nothing was touched.
    assert (site / "PySide6" / "designer.exe").exists()


def test_prune_refuses_when_a_required_file_is_missing(tmp_path):
    files = [f for f in _KEEP + _DROP + _OTHER if not f.endswith("Qt6Svg.dll")]
    site = _fake_site_packages(tmp_path, files)
    with pytest.raises(wb.BuildError, match="Qt6Svg.dll"):
        wb.prune_site_packages(site)


# --- DLL closure ----------------------------------------------------------------------


def test_check_dll_closure_flags_only_removed_dependencies(tmp_path):
    app = tmp_path / "app"
    (app / "Lib").mkdir(parents=True)
    for name in ("python313.dll", "Lib/QtGui.pyd", "Lib/Qt6Gui.dll"):
        (app / name).write_bytes(b"x")
    before = {"python313.dll", "qtgui.pyd", "qt6gui.dll", "qt6network.dll", "opengl32sw.dll"}
    imports = {
        "QtGui.pyd": ["Qt6Gui.dll", "python313.dll", "KERNEL32.dll"],
        "Qt6Gui.dll": ["Qt6Network.dll", "DWrite.dll", "icuuc.dll"],
        "python313.dll": ["VCRUNTIME140.dll"],
    }
    problems = wb.check_dll_closure(app, before, imports_of=lambda p: imports[p.name])
    # Qt6Network was in the tree and is gone → flagged. System DLLs never were → ignored.
    assert problems == {"qt6gui.dll": ["Qt6Network.dll"]}


def test_check_dll_closure_passes_for_a_closed_tree(tmp_path):
    app = tmp_path / "app"
    app.mkdir()
    for name in ("a.dll", "b.dll"):
        (app / name).write_bytes(b"x")
    problems = wb.check_dll_closure(
        app, {"a.dll", "b.dll", "c.dll"}, imports_of=lambda p: ["b.dll", "user32.dll"]
    )
    assert problems == {}


# --- PE import reader -----------------------------------------------------------------


def _fake_pe(imports: list[str], delay: list[str] = ()) -> bytes:
    """Build a minimal PE32+ image with import and delay-import directories."""
    sec_rva, sec_off = 0x1000, 0x200
    blob = bytearray()

    def add(chunk: bytes) -> int:
        offset = len(blob)
        blob.extend(chunk)
        return offset

    name_rvas = [sec_rva + add(n.encode() + b"\0") for n in imports]
    delay_rvas = [sec_rva + add(n.encode() + b"\0") for n in delay]
    while len(blob) % 8:
        blob.append(0)
    import_rva = sec_rva + len(blob)
    for rva in name_rvas:
        add(struct.pack("<IIIII", 0x2000, 0, 0, rva, 0x3000))
    add(bytes(20))  # terminator
    delay_rva = sec_rva + len(blob) if delay else 0
    for rva in delay_rvas:
        add(struct.pack("<IIIIIIII", 1, rva, 0, 0, 0, 0, 0, 0))
    if delay:
        add(bytes(32))

    dos = bytearray(0x40)
    dos[:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, 0x40)
    coff = struct.pack("<HHIIIHH", 0x8664, 1, 0, 0, 0, 240, 0x22)
    opt = bytearray(240)
    struct.pack_into("<H", opt, 0, 0x20B)  # PE32+
    struct.pack_into("<I", opt, 108, 16)  # NumberOfRvaAndSizes
    struct.pack_into("<II", opt, 112 + 1 * 8, import_rva, 20 * (len(imports) + 1))
    struct.pack_into("<II", opt, 112 + 13 * 8, delay_rva, 32 * (len(delay) + 1) if delay else 0)
    section = bytearray(40)
    section[:5] = b".data"
    struct.pack_into("<IIII", section, 8, len(blob), sec_rva, len(blob), sec_off)
    header = dos + b"PE\0\0" + coff + opt + section
    header += bytes(sec_off - len(header))
    return bytes(header) + bytes(blob)


def test_pe_imports_reads_import_and_delay_import_tables(tmp_path):
    pe = tmp_path / "fake.pyd"
    pe.write_bytes(_fake_pe(["python313.dll", "KERNEL32.dll"], ["Qt6Svg.dll"]))
    assert wb.pe_imports(pe) == ["python313.dll", "KERNEL32.dll", "Qt6Svg.dll"]


def test_pe_imports_handles_no_imports_and_non_pe_files(tmp_path):
    empty = tmp_path / "empty.dll"
    empty.write_bytes(_fake_pe([]))
    assert wb.pe_imports(empty) == []
    text = tmp_path / "notes.dll"
    text.write_bytes(b"this is not a PE file")
    assert wb.pe_imports(text) == []


# --- zip layout -----------------------------------------------------------------------


def _good_members(top="minidspqt-1.1.0"):
    return [
        f"{top}/minidspqt.exe",
        f"{top}/minidspqt-debug.cmd",
        f"{top}/python313.dll",
        f"{top}/python313._pth",
        f"{top}/python313.zip",
        f"{top}/Lib/site-packages/minidspqt/resources/blank.unt",
        f"{top}/Lib/site-packages/minidsp_linux_qt-1.1.0.dist-info/METADATA",
        f"{top}/Lib/site-packages/PySide6/QtWidgets.pyd",
        f"{top}/Lib/site-packages/PySide6/Qt6Widgets.dll",
        f"{top}/Lib/site-packages/PySide6/plugins/platforms/qwindows.dll",
        f"{top}/Lib/site-packages/shiboken6/shiboken6.abi3.dll",
        f"{top}/Lib/site-packages/hid.cp313-win_amd64.pyd",
    ]


def test_check_zip_layout_accepts_a_complete_tree():
    assert wb.check_zip_layout(_good_members(), "minidspqt-1.1.0", "3.13.15", "1.1.0") == []


def test_check_zip_layout_reports_missing_forbidden_and_stray_entries():
    members = [m for m in _good_members() if "blank.unt" not in m and "hid." not in m]
    members += ["minidspqt-1.1.0/Lib/site-packages/PySide6/qml/x.dll", "README.txt"]
    problems = wb.check_zip_layout(members, "minidspqt-1.1.0", "3.13.15", "1.1.0")
    text = "\n".join(problems)
    assert "blank.unt" in text
    assert "hid" in text
    assert "prune failed" in text
    assert "README.txt" in text
